version: v1
models:
  embedding: intfloat/e5-small-v2
  reranker: null
retrieval:
  bm25_k: 50
  embed_k: 50
  candidate_k: 12
  final_k: 8
  mmr_lambda: 0.7
thresholds:
  strict: 0.35
  lenient: 0.25
filters:
  role_level: junior
  domain: tech
vault:
  allowlist:
    - "Research Article 03.pdf"
  index_dir: "./vault_index/"
